# mini setup, all local
# create file docker-compose.yml and .env in one folder
# install docker with script
# call for starting : docker compose up -d 
# call for stopping : docker compose down   
# make .env file with NEO4J_PASSWORD=xxx
# Dashboard: http://localhost:5005/
# neo4jDB:   http://localhost:7474/browser/
# connect:   bolt://127.0.0.1:7687
services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt (WebSocket)
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data

  neodash:
    image: neo4jlabs/neodash:latest
    container_name: neodash
    depends_on: [neo4j]
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      NEO4J_URI: "bolt://127.0.0.1:7687"   
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
      STANDALONE: "true"

volumes:
  neo4j_data:
